/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_WAKE_UP_CONFIG_H_
#define _CC_WAKE_UP_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_wake_up_configuration Command Class Wake Up Configuration
 * Command Class Wake Up Configuration
 *
 * \addtogroup command_class_wake_up_configuration
 * @{
 */

/**
 * Default sleep time between Wake Up Notifications <1..255:1>
 *
 */
#if !defined(CC_WAKE_UP_CONFIG_DEFAULT_SLEEP_TIME_SEC)
#define CC_WAKE_UP_CONFIG_DEFAULT_SLEEP_TIME_SEC  300
#endif /* !defined(CC_WAKE_UP_CONFIG_DEFAULT_SLEEP_TIME_SEC) */

/**
 * Minimum sleep time between Wake Up Notifications <20..86400:1>
 *
 */
#if !defined(CC_WAKE_UP_CONFIG_MINIMUM_SLEEP_TIME_SEC)
#define CC_WAKE_UP_CONFIG_MINIMUM_SLEEP_TIME_SEC  20
#endif /* !defined(CC_WAKE_UP_CONFIG_MINIMUM_SLEEP_TIME_SEC) */

/**
 * Maximum sleep time between Wake Up Notifications <20..86400:1>
 *
 */
#if !defined(CC_WAKE_UP_CONFIG_MAXIMUM_SLEEP_TIME_SEC)
#define CC_WAKE_UP_CONFIG_MAXIMUM_SLEEP_TIME_SEC  86400
#endif /* !defined(CC_WAKE_UP_CONFIG_MAXIMUM_SLEEP_TIME_SEC) */

/**
 * Sleep step time <1..255:1>
 *
 */
#if !defined(CC_WAKE_UP_CONFIG_SLEEP_STEP_TIME_SEC)
#define CC_WAKE_UP_CONFIG_SLEEP_STEP_TIME_SEC  20
#endif /* !defined(CC_WAKE_UP_CONFIG_SLEEP_STEP_TIME_SEC) */

/**@}*/ /* \addtogroup command_class_wake_up_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_WAKE_UP_CONFIG_H_ */
