/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_NOTIFICATION_CONFIG_H_
#define _CC_NOTIFICATION_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup max_notifications Command Class Notification- notifications configuration
 * Command Class Notification- notifications configuration
 *
 * \addtogroup max_notifications
 * @{
 */

/**
 * Max number of notifications <1..255:1>
 *
 * Maximum number of notifications supported by application.
 */
#if !defined(CC_NOTIFICATION_MAX_NOTIFICATIONS)
#define CC_NOTIFICATION_MAX_NOTIFICATIONS  1
#endif /* !defined(CC_NOTIFICATION_MAX_NOTIFICATIONS) */

/**@}*/ /* \addtogroup max_notifications */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_NOTIFICATION_CONFIG_H_ */
