/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_BINARY_SWITCH_CONFIG_H_
#define _CC_BINARY_SWITCH_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_binary_switch_configuration Command Class Binary Switch Configuration
 * Command Class Binary Switch Configuration
 *
 * \addtogroup command_class_binary_switch_configuration
 * @{
 */

/**
 * Factory default duration in seconds <1..255:1>
 *
 * Factory default duration in seconds
 */
#if !defined(CC_BINARY_SWITCH_CONFIG_DEFAULT_DURATION)
#define CC_BINARY_SWITCH_CONFIG_DEFAULT_DURATION  0
#endif /* !defined(CC_BINARY_SWITCH_CONFIG_DEFAULT_DURATION) */

/**@}*/ /* \addtogroup command_class_binary_switch_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_BINARY_SWITCH_CONFIG_H_ */
