/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_H_
#define _ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup zaf_event_distributor_core_configuration ZAF Event Distributor Core Configuration
 * ZAF Event Distributor Core Configuration
 *
 * \addtogroup zaf_event_distributor_core_configuration
 * @{
 */

/**
 * Timeout (in ms) when waiting for event <1..4294967295:1>
 *
 */
#if !defined(ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_TIMEOUT)
#define ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_TIMEOUT  4294967295
#endif /* !defined(ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_TIMEOUT) */

/**@}*/ /* \addtogroup zaf_event_distributor_core_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _ZAF_EVENT_DISTRIBUTOR_CORE_CONFIG_H_ */
