/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_H_
#define _ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup zaf_event_distributor_soc_configuration ZAF Event Distributor Core Configuration
 * ZAF Event Distributor Core Configuration
 *
 * \addtogroup zaf_event_distributor_soc_configuration
 * @{
 */

/**
 * Application event queue size <1..255:1>
 *
 */
#if !defined(ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_APP_QUEUE_SIZE)
#define ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_APP_QUEUE_SIZE  5
#endif /* !defined(ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_APP_QUEUE_SIZE) */

/**
 * Command Class event queue size <1..255:1>
 *
 */
#if !defined(ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_CC_QUEUE_SIZE)
#define ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_CC_QUEUE_SIZE  2
#endif /* !defined(ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_CC_QUEUE_SIZE) */

/**@}*/ /* \addtogroup zaf_event_distributor_soc_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _ZAF_EVENT_DISTRIBUTOR_SOC_CONFIG_H_ */
