/// ****************************************************************************
/// SPDX-License-Identifier: LicenseRef-TridentMSLA
/// SPDX-FileCopyrightText: 2025 Trident IoT, LLC <https://www.tridentiot.com>
/// ***************************************************************************

#include "ZW_region_rf_definitions.h"

/* Z-Wave Region RF setup definitions */

// Z-Wave Region ANZ RF definitions
#define RF_FREQ_STRING_ANZ        "ANZ"
#define RF_PROTOCOL_MODE_ANZ      ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_ANZ    3
#define RF_FREQ_KHZ_CH0_ANZ       919800UL
#define RF_FREQ_KHZ_CH1_ANZ       921400UL
#define RF_FREQ_KHZ_CH2_ANZ       921400UL
#define RF_FIXED_RX_CHANNEL_ANZ   1
#define RF_FREQUENCIES_KHZ_ANZ    {RF_FREQ_KHZ_CH0_ANZ, RF_FREQ_KHZ_CH1_ANZ, RF_FREQ_KHZ_CH2_ANZ, 0}
#define RF_BAUDRATE_CH0_ANZ       ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_ANZ       ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_ANZ       ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_ANZ          {RF_BAUDRATE_CH0_ANZ, RF_BAUDRATE_CH1_ANZ, RF_BAUDRATE_CH2_ANZ, 0}
#define LBT_RSSI_LEVEL_ANZ        RSSI_65DB_LEVEL
#define LBT_TIME_ANZ              128
#define CHANNEL_LOCK_TIME_ANZ     0
#define CHANNEL_TRANSMIT_TIME_ANZ 0
#define USE_LR_BACKUP_CHANNEL_ANZ 0
#define USE_FRAGMENTED_BEAM_ANZ   RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_ANZ  RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region EU RF definitions
#define RF_FREQ_STRING_EU         "EU"
#define RF_PROTOCOL_MODE_EU       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_EU     3
#define RF_FREQ_KHZ_CH0_EU        869850UL
#define RF_FREQ_KHZ_CH1_EU        868400UL
#define RF_FREQ_KHZ_CH2_EU        868400UL
#define RF_FIXED_RX_CHANNEL_EU    1
#define RF_FREQUENCIES_KHZ_EU     {RF_FREQ_KHZ_CH0_EU, RF_FREQ_KHZ_CH1_EU, RF_FREQ_KHZ_CH2_EU, 0}
#define RF_BAUDRATE_CH0_EU        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_EU        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_EU        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_EU           {RF_BAUDRATE_CH0_EU, RF_BAUDRATE_CH1_EU, RF_BAUDRATE_CH2_EU, 0}
#define LBT_RSSI_LEVEL_EU         RSSI_65DB_LEVEL
#define LBT_TIME_EU               128
#define CHANNEL_LOCK_TIME_EU      0
#define CHANNEL_TRANSMIT_TIME_EU  0
#define USE_LR_BACKUP_CHANNEL_EU  0
#define USE_FRAGMENTED_BEAM_EU    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_EU   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region HK RF definitions
#define RF_FREQ_STRING_HK         "HK"
#define RF_PROTOCOL_MODE_HK       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_HK     3
#define RF_FREQ_KHZ_CH0_HK        919800UL
#define RF_FREQ_KHZ_CH1_HK        919800UL
#define RF_FREQ_KHZ_CH2_HK        919800UL
#define RF_FIXED_RX_CHANNEL_HK    1
#define RF_FREQUENCIES_KHZ_HK     {RF_FREQ_KHZ_CH0_HK, RF_FREQ_KHZ_CH1_HK, RF_FREQ_KHZ_CH2_HK, 0}
#define RF_BAUDRATE_CH0_HK        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_HK        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_HK        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_HK           {RF_BAUDRATE_CH0_HK, RF_BAUDRATE_CH1_HK, RF_BAUDRATE_CH2_HK, 0}
#define LBT_RSSI_LEVEL_HK         RSSI_65DB_LEVEL
#define LBT_TIME_HK               128
#define CHANNEL_LOCK_TIME_HK      0
#define CHANNEL_TRANSMIT_TIME_HK  0
#define USE_LR_BACKUP_CHANNEL_HK  0
#define USE_FRAGMENTED_BEAM_HK    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_HK   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region IL RF definitions
#define RF_FREQ_STRING_IL         "IL"
#define RF_PROTOCOL_MODE_IL       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_IL     3
#define RF_FREQ_KHZ_CH0_IL        916000UL
#define RF_FREQ_KHZ_CH1_IL        916000UL
#define RF_FREQ_KHZ_CH2_IL        916000UL
#define RF_FIXED_RX_CHANNEL_IL    1
#define RF_FREQUENCIES_KHZ_IL     {RF_FREQ_KHZ_CH0_IL, RF_FREQ_KHZ_CH1_IL, RF_FREQ_KHZ_CH2_IL, 0}
#define RF_BAUDRATE_CH0_IL        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_IL        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_IL        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_IL           {RF_BAUDRATE_CH0_IL, RF_BAUDRATE_CH1_IL, RF_BAUDRATE_CH2_IL, 0}
#define LBT_RSSI_LEVEL_IL         RSSI_65DB_LEVEL
#define LBT_TIME_IL               128
#define CHANNEL_LOCK_TIME_IL      0
#define CHANNEL_TRANSMIT_TIME_IL  0
#define USE_LR_BACKUP_CHANNEL_IL  0
#define USE_FRAGMENTED_BEAM_IL    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_IL   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region IN RF definitions
#define RF_FREQ_STRING_IN         "IN"
#define RF_PROTOCOL_MODE_IN       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_IN     3
#define RF_FREQ_KHZ_CH0_IN        865200UL
#define RF_FREQ_KHZ_CH1_IN        865200UL
#define RF_FREQ_KHZ_CH2_IN        865200UL
#define RF_FIXED_RX_CHANNEL_IN    1
#define RF_FREQUENCIES_KHZ_IN     {RF_FREQ_KHZ_CH0_IN, RF_FREQ_KHZ_CH1_IN, RF_FREQ_KHZ_CH2_IN, 0}
#define RF_BAUDRATE_CH0_IN        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_IN        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_IN        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_IN           {RF_BAUDRATE_CH0_IN, RF_BAUDRATE_CH1_IN, RF_BAUDRATE_CH2_IN, 0}
#define LBT_RSSI_LEVEL_IN         RSSI_65DB_LEVEL
#define LBT_TIME_IN               128
#define CHANNEL_LOCK_TIME_IN      0
#define CHANNEL_TRANSMIT_TIME_IN  0
#define USE_LR_BACKUP_CHANNEL_IN  0
#define USE_FRAGMENTED_BEAM_IN    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_IN   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region MY RF definitions
#define RF_FREQ_STRING_MY         "MY"
#define RF_PROTOCOL_MODE_MY       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_MY     3
#define RF_FREQ_KHZ_CH0_MY        868100UL
#define RF_FREQ_KHZ_CH1_MY        868100UL
#define RF_FREQ_KHZ_CH2_MY        868100UL
#define RF_FIXED_RX_CHANNEL_MY    1
#define RF_FREQUENCIES_KHZ_MY     {RF_FREQ_KHZ_CH0_MY, RF_FREQ_KHZ_CH1_MY, RF_FREQ_KHZ_CH2_MY, 0}
#define RF_BAUDRATE_CH0_MY        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_MY        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_MY        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_MY           {RF_BAUDRATE_CH0_MY, RF_BAUDRATE_CH1_MY, RF_BAUDRATE_CH2_MY, 0}
#define LBT_RSSI_LEVEL_MY         RSSI_65DB_LEVEL
#define LBT_TIME_MY               128
#define CHANNEL_LOCK_TIME_MY      0
#define CHANNEL_TRANSMIT_TIME_MY  0
#define USE_LR_BACKUP_CHANNEL_MY  0
#define USE_FRAGMENTED_BEAM_MY    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_MY   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region US RF definitions
#define RF_FREQ_STRING_US         "US"
#define RF_PROTOCOL_MODE_US       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_US     3
#define RF_FREQ_KHZ_CH0_US        916000UL
#define RF_FREQ_KHZ_CH1_US        908400UL
#define RF_FREQ_KHZ_CH2_US        908400UL
#define RF_FIXED_RX_CHANNEL_US    1
#define RF_FREQUENCIES_KHZ_US     {RF_FREQ_KHZ_CH0_US, RF_FREQ_KHZ_CH1_US, RF_FREQ_KHZ_CH2_US, 0}
#define RF_BAUDRATE_CH0_US        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_US        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_US        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_US           {RF_BAUDRATE_CH0_US, RF_BAUDRATE_CH1_US, RF_BAUDRATE_CH2_US, 0}
#define LBT_RSSI_LEVEL_US         RSSI_75DB_LEVEL
#define LBT_TIME_US               128
#define CHANNEL_LOCK_TIME_US      0
#define CHANNEL_TRANSMIT_TIME_US  0
#define USE_LR_BACKUP_CHANNEL_US  0
#define USE_FRAGMENTED_BEAM_US    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_US   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region RU RF definitions
#define RF_FREQ_STRING_RU         "RU"
#define RF_PROTOCOL_MODE_RU       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_RU     3
#define RF_FREQ_KHZ_CH0_RU        869000UL
#define RF_FREQ_KHZ_CH1_RU        869000UL
#define RF_FREQ_KHZ_CH2_RU        869000UL
#define RF_FIXED_RX_CHANNEL_RU    1
#define RF_FREQUENCIES_KHZ_RU     {RF_FREQ_KHZ_CH0_RU, RF_FREQ_KHZ_CH1_RU, RF_FREQ_KHZ_CH2_RU, 0}
#define RF_BAUDRATE_CH0_RU        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_RU        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_RU        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_RU           {RF_BAUDRATE_CH0_RU, RF_BAUDRATE_CH1_RU, RF_BAUDRATE_CH2_RU, 0}
#define LBT_RSSI_LEVEL_RU         RSSI_65DB_LEVEL
#define LBT_TIME_RU               128
#define CHANNEL_LOCK_TIME_RU      0
#define CHANNEL_TRANSMIT_TIME_RU  0
#define USE_LR_BACKUP_CHANNEL_RU  0
#define USE_FRAGMENTED_BEAM_RU    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_RU   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region CN RF definitions
#define RF_FREQ_STRING_CN         "CN"
#define RF_PROTOCOL_MODE_CN       ZPAL_RADIO_PROTOCOL_MODE_1
#define RF_NUMBER_CHANNELS_CN     3
#define RF_FREQ_KHZ_CH0_CN        868400UL
#define RF_FREQ_KHZ_CH1_CN        868400UL
#define RF_FREQ_KHZ_CH2_CN        868400UL
#define RF_FIXED_RX_CHANNEL_CN    1
#define RF_FREQUENCIES_KHZ_CN     {RF_FREQ_KHZ_CH0_CN, RF_FREQ_KHZ_CH1_CN, RF_FREQ_KHZ_CH2_CN, 0}
#define RF_BAUDRATE_CH0_CN        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_CN        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_CN        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATES_CN           {RF_BAUDRATE_CH0_CN, RF_BAUDRATE_CH1_CN, RF_BAUDRATE_CH2_CN, 0}
#define LBT_RSSI_LEVEL_CN         RSSI_65DB_LEVEL
#define LBT_TIME_CN               128
#define CHANNEL_LOCK_TIME_CN      0
#define CHANNEL_TRANSMIT_TIME_CN  0
#define USE_LR_BACKUP_CHANNEL_CN  0
#define USE_FRAGMENTED_BEAM_CN    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_CN   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region EU_LR RF definitions
#define RF_FREQ_STRING_EU_LR         "EU_LR"
#define RF_PROTOCOL_MODE_EU_LR       ZPAL_RADIO_PROTOCOL_MODE_3
#define RF_NUMBER_CHANNELS_EU_LR     4
#define RF_FREQ_KHZ_CH0_EU_LR        869850UL
#define RF_FREQ_KHZ_CH1_EU_LR        868400UL
#define RF_FREQ_KHZ_CH2_EU_LR        868400UL
#define RF_FREQ_KHZ_CH3_EU_LR        864000UL
#define RF_FIXED_RX_CHANNEL_EU_LR    3
#define RF_FREQUENCIES_KHZ_EU_LR     {RF_FREQ_KHZ_CH0_EU_LR, RF_FREQ_KHZ_CH1_EU_LR, RF_FREQ_KHZ_CH2_EU_LR, RF_FREQ_KHZ_CH3_EU_LR}
#define RF_BAUDRATE_CH0_EU_LR        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_EU_LR        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_EU_LR        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATE_CH3_EU_LR        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_EU_LR           {RF_BAUDRATE_CH0_EU_LR, RF_BAUDRATE_CH1_EU_LR, RF_BAUDRATE_CH2_EU_LR, RF_BAUDRATE_CH3_EU_LR}
#define LBT_RSSI_LEVEL_EU_LR         RSSI_65DB_LEVEL
#define LBT_TIME_EU_LR               128
#define CHANNEL_LOCK_TIME_EU_LR      0
#define CHANNEL_TRANSMIT_TIME_EU_LR  0
#define USE_LR_BACKUP_CHANNEL_EU_LR  0
#define USE_FRAGMENTED_BEAM_EU_LR    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_EU_LR   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region EU_LR_BACKUP RF definitions
#define RF_FREQ_STRING_EU_LR_BACKUP         "EU_LR_BACKUP"
#define RF_PROTOCOL_MODE_EU_LR_BACKUP       ZPAL_RADIO_PROTOCOL_MODE_3
#define RF_NUMBER_CHANNELS_EU_LR_BACKUP     4
#define RF_FREQ_KHZ_CH0_EU_LR_BACKUP        869850UL
#define RF_FREQ_KHZ_CH1_EU_LR_BACKUP        868400UL
#define RF_FREQ_KHZ_CH2_EU_LR_BACKUP        868400UL
#define RF_FREQ_KHZ_CH3_EU_LR_BACKUP        866000UL
#define RF_FIXED_RX_CHANNEL_EU_LR_BACKUP    3
#define RF_FREQUENCIES_KHZ_EU_LR_BACKUP     {RF_FREQ_KHZ_CH0_EU_LR_BACKUP, RF_FREQ_KHZ_CH1_EU_LR_BACKUP, RF_FREQ_KHZ_CH2_EU_LR_BACKUP, RF_FREQ_KHZ_CH3_EU_LR_BACKUP}
#define RF_BAUDRATE_CH0_EU_LR_BACKUP        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_EU_LR_BACKUP        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_EU_LR_BACKUP        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATE_CH3_EU_LR_BACKUP        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_EU_LR_BACKUP           {RF_BAUDRATE_CH0_EU_LR_BACKUP, RF_BAUDRATE_CH1_EU_LR_BACKUP, RF_BAUDRATE_CH2_EU_LR_BACKUP, RF_BAUDRATE_CH3_EU_LR_BACKUP}
#define LBT_RSSI_LEVEL_EU_LR_BACKUP         RSSI_65DB_LEVEL
#define LBT_TIME_EU_LR_BACKUP               128
#define CHANNEL_LOCK_TIME_EU_LR_BACKUP      0
#define CHANNEL_TRANSMIT_TIME_EU_LR_BACKUP  0
#define USE_LR_BACKUP_CHANNEL_EU_LR_BACKUP  1
#define USE_FRAGMENTED_BEAM_EU_LR_BACKUP    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_EU_LR_BACKUP   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region EU_LR_END_DEVICE RF definitions
#define RF_FREQ_STRING_EU_LR_END_DEVICE         "EU_LR_END_DEVICE"
#define RF_PROTOCOL_MODE_EU_LR_END_DEVICE       ZPAL_RADIO_PROTOCOL_MODE_4
#define RF_NUMBER_CHANNELS_EU_LR_END_DEVICE     2
#define RF_FREQ_KHZ_CH0_EU_LR_END_DEVICE        864000UL
#define RF_FREQ_KHZ_CH1_EU_LR_END_DEVICE        866000UL
#define RF_FIXED_RX_CHANNEL_EU_LR_END_DEVICE    0
#define RF_FREQUENCIES_KHZ_EU_LR_END_DEVICE     {RF_FREQ_KHZ_CH0_EU_LR_END_DEVICE, RF_FREQ_KHZ_CH1_EU_LR_END_DEVICE, 0, 0}
#define RF_BAUDRATE_CH0_EU_LR_END_DEVICE        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATE_CH1_EU_LR_END_DEVICE        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_EU_LR_END_DEVICE           {RF_BAUDRATE_CH0_EU_LR_END_DEVICE, RF_BAUDRATE_CH1_EU_LR_END_DEVICE, 0, 0}
#define LBT_RSSI_LEVEL_EU_LR_END_DEVICE         RSSI_65DB_LEVEL
#define LBT_TIME_EU_LR_END_DEVICE               128
#define CHANNEL_LOCK_TIME_EU_LR_END_DEVICE      0
#define CHANNEL_TRANSMIT_TIME_EU_LR_END_DEVICE  0
#define USE_LR_BACKUP_CHANNEL_EU_LR_END_DEVICE  0
#define USE_FRAGMENTED_BEAM_EU_LR_END_DEVICE    RADIO_FRAGEMENTED_BEAM_USE
#define USE_FIXED_RX_CHANNEL_EU_LR_END_DEVICE   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region US_LR RF definitions
#define RF_FREQ_STRING_US_LR         "US_LR"
#define RF_PROTOCOL_MODE_US_LR       ZPAL_RADIO_PROTOCOL_MODE_3
#define RF_NUMBER_CHANNELS_US_LR     4
#define RF_FREQ_KHZ_CH0_US_LR        916000UL
#define RF_FREQ_KHZ_CH1_US_LR        908400UL
#define RF_FREQ_KHZ_CH2_US_LR        908400UL
#define RF_FREQ_KHZ_CH3_US_LR        912000UL
#define RF_FIXED_RX_CHANNEL_US_LR    3
#define RF_FREQUENCIES_KHZ_US_LR     {RF_FREQ_KHZ_CH0_US_LR, RF_FREQ_KHZ_CH1_US_LR, RF_FREQ_KHZ_CH2_US_LR, RF_FREQ_KHZ_CH3_US_LR}
#define RF_BAUDRATE_CH0_US_LR        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_US_LR        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_US_LR        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATE_CH3_US_LR        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_US_LR           {RF_BAUDRATE_CH0_US_LR, RF_BAUDRATE_CH1_US_LR, RF_BAUDRATE_CH2_US_LR, RF_BAUDRATE_CH3_US_LR}
#define LBT_RSSI_LEVEL_US_LR         RSSI_75DB_LEVEL
#define LBT_TIME_US_LR               128
#define CHANNEL_LOCK_TIME_US_LR      0
#define CHANNEL_TRANSMIT_TIME_US_LR  0
#define USE_LR_BACKUP_CHANNEL_US_LR  0
#define USE_FRAGMENTED_BEAM_US_LR    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_US_LR   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region US_LR_BACKUP RF definitions
#define RF_FREQ_STRING_US_LR_BACKUP         "US_LR_BACKUP"
#define RF_PROTOCOL_MODE_US_LR_BACKUP       ZPAL_RADIO_PROTOCOL_MODE_3
#define RF_NUMBER_CHANNELS_US_LR_BACKUP     4
#define RF_FREQ_KHZ_CH0_US_LR_BACKUP        916000UL
#define RF_FREQ_KHZ_CH1_US_LR_BACKUP        908400UL
#define RF_FREQ_KHZ_CH2_US_LR_BACKUP        908400UL
#define RF_FREQ_KHZ_CH3_US_LR_BACKUP        920000UL
#define RF_FIXED_RX_CHANNEL_US_LR_BACKUP    3
#define RF_FREQUENCIES_KHZ_US_LR_BACKUP     {RF_FREQ_KHZ_CH0_US_LR_BACKUP, RF_FREQ_KHZ_CH1_US_LR_BACKUP, RF_FREQ_KHZ_CH2_US_LR_BACKUP, RF_FREQ_KHZ_CH3_US_LR_BACKUP}
#define RF_BAUDRATE_CH0_US_LR_BACKUP        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_US_LR_BACKUP        ZPAL_RADIO_SPEED_40K
#define RF_BAUDRATE_CH2_US_LR_BACKUP        ZPAL_RADIO_SPEED_9600
#define RF_BAUDRATE_CH3_US_LR_BACKUP        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_US_LR_BACKUP           {RF_BAUDRATE_CH0_US_LR_BACKUP, RF_BAUDRATE_CH1_US_LR_BACKUP, RF_BAUDRATE_CH2_US_LR_BACKUP, RF_BAUDRATE_CH3_US_LR_BACKUP}
#define LBT_RSSI_LEVEL_US_LR_BACKUP         RSSI_75DB_LEVEL
#define LBT_TIME_US_LR_BACKUP               128
#define CHANNEL_LOCK_TIME_US_LR_BACKUP      0
#define CHANNEL_TRANSMIT_TIME_US_LR_BACKUP  0
#define USE_LR_BACKUP_CHANNEL_US_LR_BACKUP  1
#define USE_FRAGMENTED_BEAM_US_LR_BACKUP    RADIO_FRAGEMENTED_BEAM_DONT_USE
#define USE_FIXED_RX_CHANNEL_US_LR_BACKUP   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region US_LR_END_DEVICE RF definitions
#define RF_FREQ_STRING_US_LR_END_DEVICE         "US_LR_END_DEVICE"
#define RF_PROTOCOL_MODE_US_LR_END_DEVICE       ZPAL_RADIO_PROTOCOL_MODE_4
#define RF_NUMBER_CHANNELS_US_LR_END_DEVICE     2
#define RF_FREQ_KHZ_CH0_US_LR_END_DEVICE        912000UL
#define RF_FREQ_KHZ_CH1_US_LR_END_DEVICE        920000UL
#define RF_FIXED_RX_CHANNEL_US_LR_END_DEVICE    0
#define RF_FREQUENCIES_KHZ_US_LR_END_DEVICE     {RF_FREQ_KHZ_CH0_US_LR_END_DEVICE, RF_FREQ_KHZ_CH1_US_LR_END_DEVICE, 0, 0}
#define RF_BAUDRATE_CH0_US_LR_END_DEVICE        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATE_CH1_US_LR_END_DEVICE        ZPAL_RADIO_SPEED_100KLR
#define RF_BAUDRATES_US_LR_END_DEVICE           {RF_BAUDRATE_CH0_US_LR_END_DEVICE, RF_BAUDRATE_CH1_US_LR_END_DEVICE, 0, 0}
#define LBT_RSSI_LEVEL_US_LR_END_DEVICE         RSSI_75DB_LEVEL
#define LBT_TIME_US_LR_END_DEVICE               128
#define CHANNEL_LOCK_TIME_US_LR_END_DEVICE      0
#define CHANNEL_TRANSMIT_TIME_US_LR_END_DEVICE  0
#define USE_LR_BACKUP_CHANNEL_US_LR_END_DEVICE  0
#define USE_FRAGMENTED_BEAM_US_LR_END_DEVICE    RADIO_FRAGEMENTED_BEAM_USE
#define USE_FIXED_RX_CHANNEL_US_LR_END_DEVICE   RADIO_FIXED_RX_CHANNEL_DONT_USE

/* 3-channel systems */

// Z-Wave Region JP RF definitions
#define RF_FREQ_STRING_JP         "JP"
#define RF_PROTOCOL_MODE_JP       ZPAL_RADIO_PROTOCOL_MODE_2
#define RF_NUMBER_CHANNELS_JP     3
#define RF_FREQ_KHZ_CH0_JP        922500UL
#define RF_FREQ_KHZ_CH1_JP        923900UL
#define RF_FREQ_KHZ_CH2_JP        926300UL
#define RF_FIXED_RX_CHANNEL_JP    0
#define RF_FREQUENCIES_KHZ_JP     {RF_FREQ_KHZ_CH0_JP, RF_FREQ_KHZ_CH1_JP, RF_FREQ_KHZ_CH2_JP, 0}
#define RF_BAUDRATE_CH0_JP        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_JP        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH2_JP        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATES_JP           {RF_BAUDRATE_CH0_JP, RF_BAUDRATE_CH1_JP, RF_BAUDRATE_CH2_JP, 0}
#define LBT_RSSI_LEVEL_JP         RSSI_80DB_LEVEL
#define LBT_TIME_JP               128
#define CHANNEL_LOCK_TIME_JP      2
#define CHANNEL_TRANSMIT_TIME_JP  400
#define USE_LR_BACKUP_CHANNEL_JP  0
#define USE_FRAGMENTED_BEAM_JP    RADIO_FRAGEMENTED_BEAM_USE
#define USE_FIXED_RX_CHANNEL_JP   RADIO_FIXED_RX_CHANNEL_DONT_USE

// Z-Wave Region KR RF definitions
#define RF_FREQ_STRING_KR         "KR"
#define RF_PROTOCOL_MODE_KR    	  ZPAL_RADIO_PROTOCOL_MODE_2
#define RF_NUMBER_CHANNELS_KR     3
#define RF_FREQ_KHZ_CH0_KR        920900UL
#define RF_FREQ_KHZ_CH1_KR        921700UL
#define RF_FREQ_KHZ_CH2_KR        923100UL
#define RF_FIXED_RX_CHANNEL_KR    0
#define RF_FREQUENCIES_KHZ_KR     {RF_FREQ_KHZ_CH0_KR, RF_FREQ_KHZ_CH1_KR, RF_FREQ_KHZ_CH2_KR, 0}
#define RF_BAUDRATE_CH0_KR        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH1_KR        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATE_CH2_KR        ZPAL_RADIO_SPEED_100K
#define RF_BAUDRATES_KR           {RF_BAUDRATE_CH0_KR, RF_BAUDRATE_CH1_KR, RF_BAUDRATE_CH2_KR, 0}
#define LBT_RSSI_LEVEL_KR         RSSI_65DB_LEVEL
#define LBT_TIME_KR               5000
#define CHANNEL_LOCK_TIME_KR      50
#define CHANNEL_TRANSMIT_TIME_KR  4000
#define USE_LR_BACKUP_CHANNEL_KR  0
#define USE_FRAGMENTED_BEAM_KR    RADIO_FRAGEMENTED_BEAM_USE
#define USE_FIXED_RX_CHANNEL_KR   RADIO_FIXED_RX_CHANNEL_DONT_USE

/* Region specific radio setup */

#define ZWAVE_REGION_RADIO_SETUP(region)\
  const zw_region_rf_setup_t ZW_REGION_SPECIFIC_##region =\
  {\
    .protocolMode = RF_PROTOCOL_MODE_##region,\
    .LBTRssiLevel = LBT_RSSI_LEVEL_##region,\
    .LBTRssiTime = LBT_TIME_##region,\
    .LBTChannelLockTime = CHANNEL_LOCK_TIME_##region,\
    .LBTChannelTxTime = CHANNEL_TRANSMIT_TIME_##region,\
    .useFragementedBeam = USE_FRAGMENTED_BEAM_##region,\
    .use_fixed_rx_channel = USE_FIXED_RX_CHANNEL_##region,\
    .use_lr_backup_channel = USE_LR_BACKUP_CHANNEL_##region,\
    .channel_count = RF_NUMBER_CHANNELS_##region,\
    .channel_frequency_khz = RF_FREQUENCIES_KHZ_##region,\
    .channel_baudrate = RF_BAUDRATES_##region,\
    .fixed_rx_channel = RF_FIXED_RX_CHANNEL_##region,\
  }

/*
    Multispeed legacy (channel config 2 - R1, R2, R3) Z-Wave regions
 */

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_EU
ZWAVE_REGION_RADIO_SETUP(EU);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_US
ZWAVE_REGION_RADIO_SETUP(US);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_ANZ
ZWAVE_REGION_RADIO_SETUP(ANZ);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_HK
ZWAVE_REGION_RADIO_SETUP(HK);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_IN
ZWAVE_REGION_RADIO_SETUP(IN);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_IL
ZWAVE_REGION_RADIO_SETUP(IL);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_RU
ZWAVE_REGION_RADIO_SETUP(RU);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_CN
ZWAVE_REGION_RADIO_SETUP(CN);

/*
    One speed three-channel (Channel config 3 - R1, R2, R3) Z-Wave region
 */

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_JP
ZWAVE_REGION_RADIO_SETUP(JP);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_KR
ZWAVE_REGION_RADIO_SETUP(KR);

/*
    Multi speed two-channel plus Long Range channel (LR1) Z-Wave regions
 */

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_EU_LR
ZWAVE_REGION_RADIO_SETUP(EU_LR);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_US_LR;
ZWAVE_REGION_RADIO_SETUP(US_LR);

/*
    Multi speed two-channel plus backup Long Range channel (LR2) Z-Wave regions
 */

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_EU_LR_BACKUP;
ZWAVE_REGION_RADIO_SETUP(EU_LR_BACKUP);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_US_LR_BACKUP
ZWAVE_REGION_RADIO_SETUP(US_LR_BACKUP);

/*
    Z-Wave Long Range only two-channel Z-Wave regions
 */

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_EU_LR_END_DEVICE
ZWAVE_REGION_RADIO_SETUP(EU_LR_END_DEVICE);

// const ZW_RadioSetup_t ZW_REGION_SPECIFIC_US_LR_END_DEVICE
ZWAVE_REGION_RADIO_SETUP(US_LR_END_DEVICE);
