/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_USER_CODE_CONFIG_H_
#define _CC_USER_CODE_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_user_code_configuration Command Class User Code Configuration
 * Command Class User Code Configuration
 *
 * \addtogroup command_class_user_code_configuration
 * @{
 */

/**
 * Max number of user Code ID's and USER CODES <1..255:1>
 *
 */
#if !defined(CC_USER_CODE_MAX_IDS)
#define CC_USER_CODE_MAX_IDS  1
#endif /* !defined(CC_USER_CODE_MAX_IDS) */

/**
 * The default user code used by the Command Class
 *
 *
 * @remarks This defines an array of size 4 and the entries range from 0 to 255
 */
#if !defined(CC_USER_CODE_DEFAULT)
#define CC_USER_CODE_DEFAULT  { 0x33, 0x34, 0x39, 0x34 }
#endif /* !defined(CC_USER_CODE_DEFAULT) */

/**@}*/ /* \addtogroup command_class_user_code_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_USER_CODE_CONFIG_H_ */
