/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_SUPERVISION_CONFIG_H_
#define _CC_SUPERVISION_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_supervision_configuration Command Class Supervision Configuration
 * Command Class Supervision Configuration
 *
 * \addtogroup command_class_supervision_configuration
 * @{
 */

/**
 * Status updates enabled
 *
 * Defines whether Status Updates supported or not
 */
#if !defined(CC_SUPERVISION_CONFIG_DEFAULT_STATUS_UPDATES_ENABLED)
#define CC_SUPERVISION_CONFIG_DEFAULT_STATUS_UPDATES_ENABLED  0
#endif /* !defined(CC_SUPERVISION_CONFIG_DEFAULT_STATUS_UPDATES_ENABLED) */

/**@}*/ /* \addtogroup command_class_supervision_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_SUPERVISION_CONFIG_H_ */
