/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _ZAF_TRANSPORT_CONFIG_H_
#define _ZAF_TRANSPORT_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup zaf_transport_configuration ZAF Transport Configuration
 * ZAF Transport Configuration
 *
 * \addtogroup zaf_transport_configuration
 * @{
 */

/**
 * Frame queue size <1..255:1>
 *
 */
#if !defined(ZAF_TRANSPORT_CONFIG_QUEUE_SIZE)
#define ZAF_TRANSPORT_CONFIG_QUEUE_SIZE  2
#endif /* !defined(ZAF_TRANSPORT_CONFIG_QUEUE_SIZE) */

/**@}*/ /* \addtogroup zaf_transport_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _ZAF_TRANSPORT_CONFIG_H_ */
