/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_FIRMWARE_UPDATE_CONFIG_H_
#define _CC_FIRMWARE_UPDATE_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup cc_firmware_update_config Command Class Firmware Update configuration
 * Command Class Firmware Update configuration
 *
 * \addtogroup cc_firmware_update_config
 * @{
 */

/**
 * OTA Cache size <1..65535:1>
 *
 * Specifies the cache size when ota multi frames is enabled
 */
#if !defined(CC_FIRMWARE_UPDATE_CONFIG_OTA_CACHE_SIZE)
#define CC_FIRMWARE_UPDATE_CONFIG_OTA_CACHE_SIZE  200
#endif /* !defined(CC_FIRMWARE_UPDATE_CONFIG_OTA_CACHE_SIZE) */

/**
 * Activation supported
 *
 * Lets the application decide whether delayed activation of the firmware is supported.
 */
#if !defined(CC_FIRMWARE_UPDATE_CONFIG_SUPPORT_ACTIVATION)
#define CC_FIRMWARE_UPDATE_CONFIG_SUPPORT_ACTIVATION  1
#endif /* !defined(CC_FIRMWARE_UPDATE_CONFIG_SUPPORT_ACTIVATION) */

/**
 * OTA Multi frames enabled
 *
 * Specifies whether CC FW Update should request multiple MD Reports in FW Update MD Get.
 */
#if !defined(CC_FIRMWARE_UPDATE_CONFIG_OTA_MULTI_FRAME)
#define CC_FIRMWARE_UPDATE_CONFIG_OTA_MULTI_FRAME  1
#endif /* !defined(CC_FIRMWARE_UPDATE_CONFIG_OTA_MULTI_FRAME) */

/**@}*/ /* \addtogroup cc_firmware_update_config */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_FIRMWARE_UPDATE_CONFIG_H_ */
