/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_COLOR_SWITCH_CONFIG_H_
#define _CC_COLOR_SWITCH_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_color_switch_configuration Command Class Color Switch Configuration
 * Command Class Color Switch Configuration
 *
 * \addtogroup command_class_color_switch_configuration
 * @{
 */

/**
 * Factory default duration in seconds <1..255:1>
 *
 * Factory default duration in seconds
 */
#if !defined(CC_COLOR_SWITCH_CONFIG_DEFAULT_DURATION_SEC)
#define CC_COLOR_SWITCH_CONFIG_DEFAULT_DURATION_SEC  2
#endif /* !defined(CC_COLOR_SWITCH_CONFIG_DEFAULT_DURATION_SEC) */

/**@}*/ /* \addtogroup command_class_color_switch_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_COLOR_SWITCH_CONFIG_H_ */
