/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_MULTI_CHANNEL_CONFIG_H_
#define _CC_MULTI_CHANNEL_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_multi_channel_configuration Command Class Multi Channel Configuration
 * Command Class Multi Channel Configuration
 *
 * \addtogroup command_class_multi_channel_configuration
 * @{
 */

/**
 * Identical endpoints
 *
 * True indicates that all endpoints are identical. False indicates that endpoints are not identical.
 */
#if !defined(CC_MULTI_CHANNEL_IDENTICAL_ENDPOINTS)
#define CC_MULTI_CHANNEL_IDENTICAL_ENDPOINTS  1
#endif /* !defined(CC_MULTI_CHANNEL_IDENTICAL_ENDPOINTS) */

/**@}*/ /* \addtogroup command_class_multi_channel_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_MULTI_CHANNEL_CONFIG_H_ */
