/**
 * @file
 * SPDX-License-Identifier: BSD-3-Clause
 * SPDX-FileCopyrightText: 2024 Z-Wave-Alliance <https://z-wavealliance.org/>
 * @note !!! THIS FILE IS AUTOGENERATED BY `generate_configurations.py` !!! DO NOT MODIFY !!!
 */

#ifndef _CC_MULTILEVEL_SENSOR_SUPPORT_CONFIG_H_
#define _CC_MULTILEVEL_SENSOR_SUPPORT_CONFIG_H_

/**
 * \defgroup configuration Configuration
 * Configuration
 *
 * \addtogroup configuration
 * @{
 */
/**
 * \defgroup command_class_multilevel_sensor_configuration Command Class Multilevel Sensor Configuration
 * Command Class Multilevel Sensor Configuration
 *
 * \addtogroup command_class_multilevel_sensor_configuration
 * @{
 */

/**
 * Autoreport period in minutes <1..3600:1>
 *
 */
#if !defined(MULTILEVEL_SENSOR_DEFAULT_AUTOREPORT_PEDIOD_MIN)
#define MULTILEVEL_SENSOR_DEFAULT_AUTOREPORT_PEDIOD_MIN  30
#endif /* !defined(MULTILEVEL_SENSOR_DEFAULT_AUTOREPORT_PEDIOD_MIN) */

/**
 * Maximum number of sensors <1..20:1>
 *
 */
#if !defined(MULTILEVEL_SENSOR_REGISTERED_SENSOR_NUMBER_LIMIT)
#define MULTILEVEL_SENSOR_REGISTERED_SENSOR_NUMBER_LIMIT  3
#endif /* !defined(MULTILEVEL_SENSOR_REGISTERED_SENSOR_NUMBER_LIMIT) */

/**@}*/ /* \addtogroup command_class_multilevel_sensor_configuration */

/**@}*/ /* \addtogroup configuration */
#endif /* _CC_MULTILEVEL_SENSOR_SUPPORT_CONFIG_H_ */
